name: CML CI/CD to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install CML
      run: |
        pip install "cml<0.6.0"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker with Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/iris-api:latest .

    - name: Push Docker image
      run: |
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/iris-api:latest

    - name: Set up GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --region ${{ secrets.GCP_REGION }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Wait for service to be ready
      run: |
        echo "Waiting for external IP..."
        sleep 60
        kubectl get svc iris-api-deployment-service -o json

    - name: Send CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        EXTERNAL_IP=$(kubectl get svc iris-api-deployment-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "## 🚀 Iris Model Deployed to GKE" > report.md
        echo "" >> report.md
        echo "**Endpoint**: http://$EXTERNAL_IP:8000/predict" >> report.md
        echo "" >> report.md
        echo "Try it with:" >> report.md
        echo "\`\`\`bash" >> report.md
        echo "curl -X POST http://$EXTERNAL_IP:8000/predict \\" >> report.md
        echo "  -H 'Content-Type: application/json' \\" >> report.md
        echo "  -d '{\"sepal_length\": 5.1, \"sepal_width\": 3.5, \"petal_length\": 1.4, \"petal_width\": 0.2}'" >> report.md
        echo "\`\`\`" >> report.md
        cml comment create --publish report.md
